# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: action.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x63tion.proto\x12\x06\x61\x63tion\"\x18\n\x06Report\x12\x0e\n\x06report\x18\x01 \x01(\t\"j\n\x06\x41\x63tion\x12 \n\x04type\x18\x01 \x01(\x0e\x32\x12.action.ActionType\x12\x0f\n\x07\x66rom_id\x18\x02 \x01(\x05\x12\r\n\x05to_id\x18\x03 \x01(\x05\x12\x1e\n\x06report\x18\x04 \x01(\x0b\x32\x0e.action.Report*A\n\nActionType\x12\x0c\n\x08\x45ND_TURN\x10\x00\x12\x13\n\x0f\x41\x43TION_INITIATE\x10\x01\x12\x10\n\x0c\x41\x43TION_REPLY\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'action_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIONTYPE._serialized_start=158
  _ACTIONTYPE._serialized_end=223
  _REPORT._serialized_start=24
  _REPORT._serialized_end=48
  _ACTION._serialized_start=50
  _ACTION._serialized_end=156
# @@protoc_insertion_point(module_scope)
